{% set name = "httmock" %}
{% set version = "1.4.0" %}
{% set sha256 = "2ac6b98e058feddd9caabb096fdfd01489bbcdce56cc234348e949c92fafcda8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/patrys/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests

test:
  imports:
    - httmock

about:
  home: https://github.com/patrys/httmock
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A mocking library for requests
  doc_url: https://github.com/patrys/httmock
  dev_url: https://github.com/patrys/httmock

extra:
  recipe-maintainers:
    - gboeing
